### ISSUE TITLE
Values names should not be related to known ressources but to sectors of values

### ISSUE THREAD

**Issue by vtexier** [galuel/Geconomicus#2]
Values names are well known resources with a known real life order of value : 

* bronze
* silver
* gold
* trophy

But when someone achieve to gather 4 "trophy", "bronze" is out of the game, except for this player who got one "bronze" as the new "top of the notch" value.
A little weird to understand for new players, because "bronze" is clearly known to have less value than "gold" in real life.
To avoid this confusion, I suggest to name the values as values "fields", that we can not easily put in hierarchy of values.

Lets say : 

* Culture
* Technology
* Food
* Energy

or : 

* Media
* Religion
* Weapons
* Computers

So when the field "energy" is completed, old "culture" is out and new "culture" become the new "hype".
People can easily understand that a new "culture" paradigm emerges.

I think it is more understandable than to explain that "bronze" is out, but a "new bronze" !!?? appears in the economy as the new goal to achieve.

**Comment by galuel** [comment]
Why not, it can be a good idea, I would put in that order : 

- Food
- Culture
- Energy
- Technology

But to be complete for such a modification, we need a special graphical symbol for each of theese cycle, to insert in the official ğeconomicus cards at the back of the cards. If We have those graphical symbols I propose we put a new graphical proposition for cards, keeping the old one, and proposing this new one. If so, we can be able in the future to propose different cycle-like card sets with different themes, that will be usefull for many relative approaches to the game.

**Comment by galuel** [comment]
First "revolution" set of cards has been done. Closed.
